"""CSS class mappings for DOCX styles."""

# DOCX style name -> CSS class mapping
STYLE_MAP = {
    # Headings
    "Heading 1": "heading-1",
    "Heading 2": "heading-2",
    "Heading 3": "heading-3",
    "Heading 4": "heading-4",
    "Heading 5": "heading-5",
    "Heading 6": "heading-6",
    "Title": "title",
    "Subtitle": "subtitle",
    # Body text
    "Normal": "body-text",
    "Body Text": "body-text",
    "Body Text 2": "body-text",
    "Body Text 3": "body-text",
    # Lists
    "List Paragraph": "list-item",
    "List Bullet": "list-item",
    "List Number": "list-item",
    # Quotes
    "Quote": "quote",
    "Intense Quote": "quote-intense",
    # Other
    "Caption": "caption",
    "Footer": "footer",
    "Header": "header",
}

DEFAULT_CSS = """/* Generated by docx-cli */

* { box-sizing: border-box; }

body {
    font-family: 'Calibri', 'Arial', sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #000;
    max-width: 8.5in;
    margin: 0 auto;
    padding: 1in;
}

.heading-1 { font-size: 24pt; font-weight: bold; margin: 24pt 0 12pt 0; color: #2e74b5; }
.heading-2 { font-size: 18pt; font-weight: bold; margin: 18pt 0 6pt 0; color: #2e74b5; }
.heading-3 { font-size: 14pt; font-weight: bold; margin: 14pt 0 6pt 0; color: #1f4d78; }
.heading-4 { font-size: 12pt; font-weight: bold; font-style: italic; margin: 12pt 0 6pt 0; color: #2e74b5; }
.heading-5 { font-size: 11pt; font-weight: bold; margin: 11pt 0 6pt 0; color: #2e74b5; }
.heading-6 { font-size: 11pt; font-weight: bold; font-style: italic; margin: 11pt 0 6pt 0; color: #1f4d78; }
.title { font-size: 28pt; font-weight: bold; margin: 0 0 12pt 0; text-align: center; }
.subtitle { font-size: 14pt; color: #5a5a5a; margin: 0 0 24pt 0; text-align: center; }
.body-text { margin: 0 0 10pt 0; }

ul, ol { margin: 0 0 10pt 0; padding-left: 36pt; }
.list-item { margin: 0 0 6pt 0; }
.bullet-list { list-style-type: disc; }
.numbered-list { list-style-type: decimal; }

.quote { margin: 10pt 36pt; font-style: italic; color: #404040; border-left: 4px solid #2e74b5; padding-left: 12pt; }
.quote-intense { margin: 10pt 36pt; font-style: italic; font-weight: bold; color: #2e74b5; border-left: 4px solid #2e74b5; padding-left: 12pt; }

table { border-collapse: collapse; margin: 10pt 0; width: 100%; }
th, td { border: 1px solid #000; padding: 6pt 12pt; text-align: left; }
th { background-color: #f0f0f0; font-weight: bold; }

strong, b { font-weight: bold; }
em, i { font-style: italic; }
u { text-decoration: underline; }

.caption { font-size: 9pt; color: #404040; text-align: center; margin: 6pt 0; }
.header, .footer { font-size: 9pt; color: #808080; }
"""


def get_css_class(style_name: str | None) -> str:
    """Get CSS class for a DOCX style name."""
    if style_name is None:
        return "body-text"
    return STYLE_MAP.get(style_name, "body-text")


def get_default_css() -> str:
    """Get the default CSS stylesheet."""
    return DEFAULT_CSS
